package Exception_Handling;

import java.util.Scanner;

public class Finally_Exception {

	public static void main(String[] args) {
		Scanner sc = new Scanner(System.in);
		System.out.println("Enter Values");
		try
		{
			int a = sc.nextInt();
			int b = sc.nextInt();
			System.out.println(c/b);
		}
		catch(Exception )
		{
			System.out.println( + "Developers exception occurs");
		}
		finally
		{
			System.out.println("This is finally block it alwys runs");
		}

	}

}
